### ISSUE TITLE
Missing SQF Commands

### ISSUE THREAD

**Issue by expung3d** [blackfisch/VSCode_SQF#2]
#### List of missing SQF commands, may be missing additional missing commands.
- ctrlSetPositionX (v1.92)
- ctrlSetPositionY (v1.92)
- ctrlSetPositionW (v1.92)
- ctrlSetPositionH (v1.92)
- tvSetColor (v0.74)
- tvCollapseAll (v0.74)
- tvExpandAll (v0.74)

**Comment by blackfisch** [comment]
This is definitely not limited to the commands above. Theere are whole sets of commands missing.

All commands and functions from these  Arma versions are currently not included:

- 1.68
- 1.70
- 1.72
- 1.76
- 1.78
- 1.82
- 1.84

**Comment by blackfisch** [comment]
TODO:

- [x] automate fetching of version commands
- [x] automate generating/updating `syntaxes/sqf.min.json`
- [x] support missing versions
  - [x] 1.68
  - [x] 1.70
  - [x] 1.72
  - [x] 1.76
  - [x] 1.78
  - [x] 1.82
  - [x] 1.84
